loggers:
  console:
    config:
      file_name: "log1.log"
      log_level: WARNING
  cloudwatch:
    config:
      log_level: ERROR
      log_group_name: /my/cool/cloudwatch/log/group
      log_stream_name: very_good_log_stream    